spring:
  application:
    name: papi-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 172.28.16.169:8848
        namespace: e257c0b1-b1a7-4af9-bf48-d2d4455dc32f
        # prod in ecs
        # dev in local       b765d215-8484-45ec-a86f-07048c01dd47
        group: ${spring.profiles.active}
        username: nacos
        password: nacos
    gateway:
      loadbalancer:
        type: LOAD
        use404: false
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true # 服务名小写
      routes:
        - id: papi-route
#          uri: http://106.15.79.18:8123
          uri: lb://papi-interface
          predicates:
            - Path=/api/**
  redis:
    port: 6379
    host: 172.28.16.169
    database: 3
    password: 907830201
host:
  nacos: 172.28.16.169:8848

dubbo:
  application:
    name: papi-gateway
  # 设置dubbo的协议为dubbo，随机分配端口
  protocol:
    name: dubbo
    port: 22223
  registry:
    # 配置注册中心为 nacos，使用的地址是 nacos://127.0.0.1:8848
    id: nacos-registry
    address: nacos://${host.nacos}
    parameters:
      # 注意 这里要在 nacos 创建名为 dubbo 的 namespace 环境
      namespace: 0850d63f-ea6a-4b57-8f5c-10ed248eb696

server:
  port: 8090
  tomcat:
    max-http-form-post-size: 10MB