spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.28.16.169:3306/papi?serverTimezone=Asia/Shanghai
    username: papi
    password: 907830201
  # redis 配置
  redis:
    port: 6379
    host: 172.28.16.169
    database: 0
    password: 907830201
  rabbitmq:
    host: 172.28.16.169
    port: 5672
    password: 123456
    username: admin
dubbo:
  application:
    name: papi-main
  # 设置dubbo的协议为dubbo，随机分配端口
  protocol:
    name: dubbo
    port: 22221
  registry:
    # 配置注册中心为 nacos，使用的地址是 nacos://127.0.0.1:8848
    id: nacos-registry
    address: nacos://${host.nacos}
    parameters:
      # 注意 这里要在 nacos 创建名为 dubbo 的 namespace 环境
      namespace: 0850d63f-ea6a-4b57-8f5c-10ed248eb696
#      group: ${spring.profiles.active} Param 'group' is illegal