spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/openAPI?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  # redis 配置
  redis:
    port: 6379
    host: 192.168.108.128
    database: 0
    password: 123456
dubbo:
  application:
    name: papi-main
  # 设置dubbo的协议为dubbo，随机分配端口
  protocol:
    name: dubbo
    port: 22221
  registry:
    # 配置注册中心为 nacos，使用的地址是 nacos://127.0.0.1:8848
    id: nacos-registry
    address: nacos://${host.nacos}
    parameters:
      # 注意 这里要在 nacos 创建名为 dubbo 的 namespace 环境
      namespace: 742651c4-5b7c-45e8-91ce-a1d2ba31cf02
#      group: ${spring.profiles.active} Param 'group' is illegal